output "resource_group_name" {
  description = "Resource group name generated by Azure naming module."
  value       = azurerm_resource_group.main.name
}

output "virtual_network_name" {
  description = "Virtual network name generated by Azure naming module."
  value       = module.vnet.name
}

output "aks_cluster_name" {
  description = "AKS cluster name."
  value       = module.naming.kubernetes_cluster.name
}

output "aks_cluster_resource_id" {
  description = "AKS cluster resource ID."
  value       = "/subscriptions/${var.subscription_id}/resourceGroups/${azurerm_resource_group.main.name}/providers/Microsoft.ContainerService/managedClusters/${module.naming.kubernetes_cluster.name}"
}
