output "resource_group_name" {
  description = "Resource group name generated by Azure naming module."
  value       = azurerm_resource_group.main.name
}

output "virtual_network_name" {
  description = "Virtual network name generated by Azure naming module."
  value       = module.vnet.name
}
