apiVersion: v1
kind: Service
metadata:
  name: {{ tpl $.Values.serviceName $ }}
spec:
  type: {{ default "ClusterIP" $.Values.service.type }}
  ports:
    - port: {{ $.Values.port }}
      targetPort: {{ $.Values.port }}
      protocol: TCP
  selector:
    app: {{ tpl $.Values.serviceName $ }}
